import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { jalankan } from '../ornament-forge/verify.mjs'

/**
 * Tabel metrik ornamen untuk browser.
 *
 * Lencana "ketebalan garis berbeda dari tema" di Studio Ornamen butuh dua angka per glyph:
 * `stroke-width` yang dipakainya dan apakah ia punya lapisan `data-draw`. Keduanya hanya ada
 * di `scripts/ornament-forge/verify.mjs`, yang **membaca berkas `.vue` dari disk** — jadi
 * tidak mungkin dijalankan di browser. Berkas ini memindahkan angkanya sekali, saat build,
 * ke satu modul yang bisa diimpor dasbor.
 *
 * **Dua sumber, dan itu bukan pilihan gaya.** `bacaBank()` di `verify.mjs` mem-parse
 * `utils/ornaments.ts` dengan dua regex: objek literal dan helper `layer(...)`. Enam puluh
 * lima aset referensi masuk bank lewat spread `...referenceOrnaments`, jadi **regex itu tidak
 * pernah melihatnya** — dan memang tidak bisa mengukurnya, karena mereka `<img>` ke berkas
 * eksternal, bukan SFC ber-`<svg>`. Setengah referensi karena itu dibaca dari
 * `packs/referensi/catalog.json`, yang sudah mencatat `bytes` tiap aset.
 *
 * Kalau kelak ada pola pendaftaran ketiga di `ornaments.ts`, yang menangkapnya adalah tes
 * cakupan di `apps/web/test/ornament-metrics.spec.ts` — ia menuntut kunci tabel ini sama
 * persis dengan kunci `ornamentBank`, dua arah.
 *
 * Jalankan: `pnpm ornament:metrics` (periksa) atau `pnpm ornament:metrics --tulis`.
 */

const root = fileURLToPath(new URL('../../', import.meta.url))
export const tujuan = `${root}apps/web/utils/ornament-metrics.ts`

/** Ambang "berkas besar", dalam byte. Di atas ini pemilih memberi lencana berat. */
export const ambangBerat = 300_000

/**
 * Metrik tiap glyph bank, tersortir supaya keluarannya tidak bergantung urutan `Object.keys`.
 *
 * `garis` kosong berarti **tidak terukur**, dan itu tidak pernah sama dengan "cocok". Hanya
 * aset referensi yang boleh kosong, dan mereka ditandai `tetap: true`.
 */
export function susunMetrik() {
  const { ukuran } = jalankan()
  const keluar = {}

  for (const [id, u] of Object.entries(ukuran)) {
    // `strokes` mencatat tiap lapisan garis, jadi satu glyph bisa melaporkan [3, 3].
    // Yang dibandingkan nilainya, bukan berapa kali ia muncul.
    keluar[id] = { garis: [...new Set(u.strokes)].sort((a, b) => a - b), rel: u.punyaDraw, bytes: u.bytes }
  }

  const katalog = JSON.parse(readFileSync(`${root}packs/referensi/catalog.json`, 'utf8'))
  for (const aset of katalog.assets) {
    keluar[aset.id] = { garis: [], rel: false, bytes: aset.bytes, tetap: true }
  }

  return Object.fromEntries(Object.entries(keluar).sort(([a], [b]) => (a < b ? -1 : 1)))
}

/**
 * Teks berkas, sebagai fungsi murni.
 *
 * Dipisah dari penulisannya dengan sengaja, meniru `rakitGlyph` di
 * `scripts/ornament-forge/emit.mjs`: gerbang kesegaran bisa membandingkan teks tanpa
 * menjalankan efek samping apa pun.
 */
export function rakit(metrik) {
  const baris = Object.entries(metrik).map(([id, m]) => {
    const tetap = m.tetap ? ', tetap: true' : ''
    return `  '${id}': { garis: [${m.garis.join(', ')}], rel: ${m.rel}, bytes: ${m.bytes}${tetap} },`
  })

  return [
    '// Generated by scripts/ornament-metrics/build.mjs. Jangan disunting tangan —',
    '// jalankan `pnpm ornament:metrics --tulis`. Dijaga apps/web/test/ornament-metrics.spec.ts.',
    '',
    '/**',
    ' * Ketebalan garis dan lapisan `data-draw` tiap glyph, diukur oleh gerbang forge.',
    ' *',
    ' * `garis` kosong berarti TIDAK TERUKUR, bukan "cocok" — hanya aset referensi yang boleh',
    ' * kosong, dan mereka membawa `tetap: true` karena paletnya terpanggang ke berkas dan tidak',
    ' * pernah mengikuti `--iv-orn-*`.',
    ' *',
    ' * Tabel ini milik dasbor. Jalur render tamu tidak boleh mengimpornya; satu gerbang',
    ' * teks-sumber di `apps/web/test/editor-imports.spec.ts` menegakkannya.',
    ' */',
    '/**',
    ' * Ambang “berkas besar”, dalam byte.',
    ' *',
    ' * Di atas ini pemilih memberi lencana berat. Angkanya hidup di sini, bukan di modul yang',
    ' * memakainya, supaya ia ikut terbit bersama byte yang diukurnya.',
    ' */',
    `export const ambangBerat = ${ambangBerat}`,
    '',
    'export interface OrnamentMetric {',
    '  /** Nilai `stroke-width` unik, tersortir. Kosong = tidak terukur. */',
    '  garis: number[]',
    '  /** Punya lapisan `data-draw`, jadi bisa ikut koreografi DrawSVG. */',
    '  rel: boolean',
    '  /** Byte sumber SFC, atau byte aset untuk entri referensi. */',
    '  bytes: number',
    '  /** Hanya entri referensi: palet terpanggang, tidak ikut palet pasangan. */',
    '  tetap?: true',
    '}',
    '',
    'export const ornamentMetrics: Record<string, OrnamentMetric> = {',
    ...baris,
    '}',
    '',
  ].join('\n')
}

function main() {
  const teks = rakit(susunMetrik())
  const tulis = process.argv.includes('--tulis')
  const sekarang = (() => {
    try { return readFileSync(tujuan, 'utf8') } catch { return null }
  })()

  if (tulis) {
    writeFileSync(tujuan, teks)
    console.log(`ditulis: ${tujuan} (${teks.split('\n').length - 1} baris)`)
    return
  }

  if (sekarang === teks) {
    console.log(`segar: ${tujuan}`)
    return
  }

  console.error(sekarang === null
    ? `belum ada: ${tujuan} — jalankan \`pnpm ornament:metrics --tulis\``
    : `basi: ${tujuan} menyimpang dari pengukuran — jalankan \`pnpm ornament:metrics --tulis\``)
  process.exitCode = 1
}

if (import.meta.url === `file://${process.argv[1]}`) main()
