import fs from 'node:fs/promises';
import path from 'node:path';
import { escapeHtml as e, extractCssUrls } from './core.mjs';
const root = path.resolve(process.argv[2] || 'docs/features/ornament-builder/sources');
const dirs = await fs.readdir(root, { withFileTypes:true });
const sites = [];
const css = 'body{margin:0;padding:32px;background:#f6f3ed;color:#263d32;font:16px/1.6 system-ui}main{max-width:1200px;margin:auto}h1{font:42px Georgia}a{color:#315d48}header{margin-bottom:32px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:18px}figure{margin:0;border:1px solid #ddd6c6;background:#fff;padding:12px;border-radius:8px}img{width:100%;height:190px;object-fit:contain;background:repeating-conic-gradient(#f5f5f5 0% 25%,#e9e9e9 0% 50%) 50%/16px 16px}figcaption{font-size:12px;overflow-wrap:anywhere}code{font-size:12px}table{border-collapse:collapse;width:100%}td,th{padding:10px;text-align:left;border-bottom:1px solid #ddd}';
for (const dir of dirs.filter(d=>d.isDirectory() && d.name!=='blobs')) {
  const loc = path.join(root,dir.name);
  let m; try { m=JSON.parse(await fs.readFile(path.join(loc,'manifest.json'),'utf8')); } catch { continue; }
  const html = await fs.readFile(path.join(loc,'rendered.html.txt'),'utf8').catch(()=> '');
  const inline = [...html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)].map(x=>x[1]).join('\n');
  const declarations = [
    ...m.assets.flatMap(a => (a.fontDeclarations||[]).map(rule=>({ source:a.url,rule }))),
    ...[...inline.matchAll(/@font-face\s*\{([^}]+)\}/g)].map(x=>({ source:m.url+'#inline-style',rule:x[1] })),
  ].map(x=>({...x, urls:extractCssUrls(x.rule,x.source)}));
  const unique = (items,key) => [...new Map(items.map(x=>[key(x),x])).values()];
  const samples = unique(m.phases.flatMap(p=>p.fonts), f=>[f.selector,f.family,f.weight,f.size].join('|'));
  const glyphFonts = unique(m.renderedFonts.flatMap(x=>x.fonts.map(f=>({...f,selector:x.selector}))), f=>[f.familyName,f.postScriptName,f.selector].join('|'));
  const fonts = { schemaVersion:1, declarations, computedSamples:samples, platformFonts:glyphFonts, note:'Declarations are not proof of use. Computed family is a candidate list; CDP platformFonts with glyphCount > 0 proves rendered glyphs in sampled nodes only.' };
  await fs.writeFile(path.join(loc,'fonts.json'),JSON.stringify(fonts,null,2));
  const images = m.assets.filter(a=>a.thumbnail);
  const downloaded=m.assets.filter(a=>a.status==='downloaded');
  const failures=m.assets.filter(a=>a.status!=='downloaded');
  const cards=images.map(a=>`<figure><a href="../${e(a.local)}"><img loading="lazy" src="../${e(a.thumbnail)}" alt="Referensi ${e(a.format)}"></a><figcaption>${e(decodeURIComponent(a.url.split('/').pop()).slice(0,100))}<br>${e(a.format)} · ${a.dimensions?.width}×${a.dimensions?.height} · ${Math.round(a.bytes/1024)} KB<br><a href="${e(a.url)}">Sumber</a> · riset saja</figcaption></figure>`).join('\n');
  await fs.writeFile(path.join(loc,'gallery.html'),`<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${e(m.id)} — arsip</title><style>${css}</style><main><header><a href="../index.html">← Semua situs</a><h1>${e(m.id)}</h1><p><a href="${e(m.url)}">Halaman sumber</a> · ${images.length} gambar · ${downloaded.length} sumber berhasil · ${failures.length} gagal/tidak didukung</p><p>Aset kompetitor untuk riset, bukan aset produksi. Galeri mencakup ornamen, foto contoh, thumbnail, dan ikon; lihat nama sumber sebelum memilih.</p><p><a href="cover.png">Cover</a> · <a href="full-page.png">Halaman penuh</a> · <a href="REPORT.md">Laporan</a> · <a href="fonts.json">Bukti font</a></p></header><div class="grid">${cards}</div></main></html>`);
  const actual=unique(glyphFonts.filter(f=>f.glyphCount>0),f=>f.familyName).map(f=>f.familyName);
  const inspection=m.inspection.map(x=>JSON.stringify(x)).join('\n\n');
  const report=`# ${m.id}\n\nSumber: ${m.url}\n\nDiambil: ${m.capturedAt}. Viewport: 390×844.\n\n## Cakupan\n\n- ${images.length} gambar dengan thumbnail; ${downloaded.length} sumber berhasil; ${failures.length} gagal/tidak didukung.\n- ${m.phases.length} fase browser, ${samples.length} sampel computed style, ${glyphFonts.length} sampel font platform.\n- Seluruh unduhan hanya untuk riset. Asal Canva tidak terverifikasi.\n\n## Font\n\n${fonts.note}\n\nFont yang terbukti merender glyph pada node yang disampel: **${actual.join(', ') || 'belum terverifikasi'}**.\n\n| Selector | Family terhitung | Weight | Size / line-height |\n|---|---|---|---|\n${samples.slice(0,45).map(f=>`| \`${f.selector.replaceAll('|','/')}\` | ${f.family.replaceAll('|','/')} | ${f.weight} | ${f.size} / ${f.lineHeight} |`).join('\n')}\n\nDeklarasi @font-face, sumber berkas, dan glyphCount lengkap: [fonts.json](fonts.json).\n\n## Motion\n\n[manifest.json](manifest.json) mencatat motion per fase: selector/layer, animation-name, durasi, easing, iterasi, transform, origin dan z-index. Fase cover/opened/scroll adalah trigger pengamatan, bukan jaminan bahwa setiap transform dipicu scroll.\n\nNama animasi yang teramati: ${[...new Set(m.motion.map(x=>x.animation).filter(x=>x!=='none'))].join(', ') || 'tidak terdeteksi pada sampel'}.\n\n## Inspect dan provenance\n\n\`\`\`json\n${inspection}\n\`\`\`\n\nString match bukan bukti eksekusi. Event sintetis tidak setara klik kanan asli. DOM dan sumber dapat dibaca pada sesi ini; belum ada bukti bahwa semua akses DevTools diblokir. Font/background di stylesheet eksternal dan cover bertumpuk perlu ditelusuri lewat Network/Computed.\n\n## Keterbatasan\n\n${m.limitations.map(x=>'- '+x).join('\n')}\n- Foto contoh/ikon termasuk inventaris; tidak semuanya ornamen.\n- Screenshot menunjukkan satu waktu; transform dapat berubah selama animasi.\n- ${m.requestFailures.length} request browser gagal/terputus; daftar ada dalam manifest.\n\n## Sumber gagal/tidak didukung\n\n${failures.map(a=>'- '+a.url+' — '+a.status+' '+(a.httpStatus||a.error||'')).join('\n') || 'Tidak ada pada inventaris yang diunduh.'}\n`;
  await fs.writeFile(path.join(loc,'REPORT.md'),report);
  sites.push({id:m.id,url:m.url,images:images.length,downloaded:downloaded.length,failed:failures.length,actualFonts:actual,coverage:m.coverage});
}
await fs.writeFile(path.join(root,'catalog.json'),JSON.stringify({schemaVersion:1,generatedAt:new Date().toISOString(),usage:'research-only',sites},null,2));
await fs.writeFile(path.join(root,'index.html'),`<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Aruna Dewa — riset ornamen</title><style>${css}</style><main><header><p>ARUNA DEWA / DESIGN RESEARCH</p><h1>Perpustakaan referensi</h1><p>Delapan studi undangan. Aset asli, tipografi, dan jejak motion; terpisah dari koleksi original Sunda.</p><a href="../originals/sunda/demo/index.html">Lihat paket Sunda original →</a></header><table><tr><th>Situs</th><th>Gambar</th><th>Unduhan</th><th>Gagal/lainnya</th></tr>${sites.map(s=>`<tr><td><a href="${s.id}/gallery.html">${e(s.id)}</a></td><td>${s.images}</td><td>${s.downloaded}</td><td>${s.failed}</td></tr>`).join('')}</table><p><a href="catalog.json">Katalog JSON</a></p></main></html>`);
console.log(JSON.stringify(sites.map(({id,images,downloaded,failed,actualFonts})=>({id,images,downloaded,failed,actualFonts})),null,2));
