#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Target SSH. Alias `aruna` dibuat oleh scripts/setup-deploy-credentials.sh.
SSH_TARGET="${SSH_TARGET:-aruna}"
API_ORIGIN="https://api.arunadewa.id"
REDIRECT_URI="$API_ORIGIN/auth/google"
REMOTE_ENV="/srv/aruna/api.env"

banner "Login Google untuk arunadewa.id"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pilih project yang selama ini dipakai di lokal"
say "OAuth client-nya sudah ada — yang belum ada cuma redirect URI produksi."
say "Jadi jangan bikin client baru: kita menambah URI ke client yang sama."
open_url "https://console.cloud.google.com/apis/credentials"
step "Di pemilih project (kiri atas), pilih project yang dipakai untuk Aruna Dewa."
step "Di daftar 'OAuth 2.0 Client IDs', pastikan ada satu client bertipe 'Web application'."
note "Kalau daftarnya kosong, Anda sedang di project yang salah — ganti project dulu."
pause "Sudah ketemu client-nya? Tekan Enter"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Izinkan aplikasi dipakai orang di luar daftar tes"
say "Selama status masih 'Testing', hanya email yang terdaftar sebagai test user"
say "yang bisa masuk. Pelanggan Anda akan ditolak dengan layar 'access blocked'."
open_url "https://console.cloud.google.com/auth/audience"
step "Buka 'Audience' (UI lama: 'OAuth consent screen')."
step "Kalau 'Publishing status' masih Testing, tekan 'PUBLISH APP' lalu konfirmasi."
note "Aman tanpa review Google: scope yang dipakai cuma openid, email, dan profile —"
note "ketiganya non-sensitive, jadi tidak ada proses verifikasi yang perlu ditunggu."
say ""
step "Lalu buka 'Branding', dan pastikan 'Authorized domains' memuat: arunadewa.id"
pause "Status sudah 'In production' dan domain sudah terdaftar? Tekan Enter"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Tambahkan redirect URI produksi"
say "Alamat ini diturunkan dari API_ORIGIN di server, bukan dari env tersendiri."
say "Google menolak login kalau berbeda satu karakter pun — termasuk garis miring."
say ""
printf '  %s%s%s\n' "$BOLD" "$REDIRECT_URI" "$RESET"
say ""
open_url "https://console.cloud.google.com/apis/credentials"
step "Klik nama client 'Web application' tadi."
step "Di 'Authorized redirect URIs', tekan '+ ADD URI' dan tempelkan alamat di atas."
warn "JANGAN hapus URI 127.0.0.1 yang sudah ada — itu yang dipakai pnpm dev."
step "Tekan SAVE."
note "'Authorized JavaScript origins' tidak perlu diisi: alur ini ditukar di server,"
note "bukan di browser."
pause "Sudah tersimpan? Tekan Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Salin Client ID dan Client Secret"
say "Keduanya ada di panel kanan halaman client yang barusan Anda simpan."
step "Salin 'Client ID' (berakhiran .apps.googleusercontent.com)."
ask GOOGLE_CLIENT_ID "Tempelkan Client ID:"
step "Salin 'Client secret'. Kalau tersembunyi, tekan ikon mata atau 'Add secret'."
ask_secret GOOGLE_CLIENT_SECRET "Tempelkan Client secret (tidak akan tampil):"

if [[ -z "${GOOGLE_CLIENT_ID:-}" || -z "${GOOGLE_CLIENT_SECRET:-}" ]]; then
  warn "Salah satu nilainya kosong. Jalankan ulang skrip ini setelah keduanya siap."
  SKIPPED+=("tulis GOOGLE_CLIENT_ID/SECRET ke $REMOTE_ENV")
  finish
  exit 1
fi
case "$GOOGLE_CLIENT_ID" in
  *.apps.googleusercontent.com) ;;
  *) warn "Client ID biasanya berakhiran .apps.googleusercontent.com — periksa lagi kalau login nanti gagal." ;;
esac

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Tulis ke server dan nyalakan ulang API"
say "Nilainya dikirim lewat stdin, bukan sebagai argumen perintah, supaya tidak"
say "pernah muncul di daftar proses server."
say ""
note "compose 'restart' tidak membaca ulang env_file — jadi yang dipakai 'up -d',"
note "yang membuat ulang container api dengan env yang baru."
say ""
if ! confirm "Tulis ke $REMOTE_ENV di $SSH_TARGET lalu buat ulang container api?"; then
  SKIPPED+=("tulis GOOGLE_CLIENT_ID/SECRET ke $REMOTE_ENV dan buat ulang container api")
  finish
  exit 0
fi

REMOTE_SCRIPT='
set -eu
IFS= read -r CID
IFS= read -r CSEC
f=/srv/aruna/api.env
cp -p "$f" "$f.bak.$(date +%Y%m%d%H%M%S)"
tmp=$(mktemp)
chmod 600 "$tmp"
grep -vE "^GOOGLE_CLIENT_(ID|SECRET)=" "$f" > "$tmp" || true
printf "GOOGLE_CLIENT_ID=%s\n" "$CID" >> "$tmp"
printf "GOOGLE_CLIENT_SECRET=%s\n" "$CSEC" >> "$tmp"
mv "$tmp" "$f"
chmod 600 "$f"
cd /srv/aruna
docker compose -f compose.prod.yaml --env-file .env --env-file .image.env up -d api
'

if printf '%s\n%s\n' "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" \
  | ssh "$SSH_TARGET" "$REMOTE_SCRIPT"; then
  printf '  %s✓ ditulis%s GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET → %s\n' "$GREEN" "$RESET" "$REMOTE_ENV"
  WRITTEN_ENV+=("GOOGLE_CLIENT_ID" "GOOGLE_CLIENT_SECRET")
else
  warn "Penulisan gagal. Cadangan api.env tidak tersentuh; container tidak diubah."
  SKIPPED+=("tulis GOOGLE_CLIENT_ID/SECRET ke $REMOTE_ENV")
  finish
  exit 1
fi

say ""
say "Menunggu API siap menerima trafik lagi…"
ready=""
for _ in $(seq 1 24); do
  if curl -fsS --max-time 5 "$API_ORIGIN/ready" >/dev/null 2>&1; then ready="ya"; break; fi
  sleep 5
done
if [[ -z "$ready" ]]; then
  warn "$API_ORIGIN/ready belum hijau setelah 2 menit."
  note "Lihat sebabnya: ssh $SSH_TARGET 'docker logs --tail=50 aruna-api-1'"
  SKIPPED+=("periksa kenapa API tidak siap setelah restart")
  finish
  exit 1
fi
printf '  %s✓%s API siap\n' "$GREEN" "$RESET"

say ""
say "Bukti terakhir — tombol Google harus melempar ke Google, bukan ke 400:"
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$API_ORIGIN/auth/google/start" || echo "000")
if [[ "$code" == "302" ]]; then
  printf '  %s✓%s /auth/google/start → 302 ke accounts.google.com\n' "$GREEN" "$RESET"
  say ""
  say "Sekarang buka https://arunadewa.id/login dan tekan tombol Google."
  note "Kalau Google menjawab 'redirect_uri_mismatch', URI-nya baru saja disimpan —"
  note "perubahan di Google Console kadang butuh beberapa menit untuk menyebar."
else
  warn "/auth/google/start menjawab $code, bukan 302."
  note "Isi pesannya: curl -s $API_ORIGIN/auth/google/start"
  SKIPPED+=("selidiki kenapa /auth/google/start masih $code")
fi

finish
