#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Semua berkas relatif terhadap akar repo, supaya `gh` menemukan repo yang benar
# dan `.env.deploy` tidak berserak di direktori mana pun wizard ini dijalankan.
if command -v git >/dev/null 2>&1 && git rev-parse --show-toplevel >/dev/null 2>&1; then
  cd "$(git rev-parse --show-toplevel)"
fi
ENV_FILE=".env.deploy"   # cocok dengan pola `.env.*` di .gitignore

ADMIN_KEY="$HOME/.ssh/aruna_admin"
DEPLOY_KEY="$HOME/.ssh/aruna_deploy"

# salin_ke_clipboard FILE — pbcopy di macOS, kalau tidak ada tampilkan isinya.
salin_ke_clipboard() {
  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$1"
    printf '  %s✓ tersalin ke clipboard%s  (%s)\n' "$GREEN" "$RESET" "$1"
  else
    note "salin baris di bawah ini:"
    printf '\n'; cat "$1"; printf '\n'
  fi
}

banner "Kredensial deploy Aruna Dewa"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Buat dua kunci SSH"
say "Dua kunci, bukan satu, dan pemisahannya disengaja:"
step "aruna_admin  — Anda masuk ke server. Berpassphrase."
step "aruna_deploy — GitHub Actions saat merilis. Tanpa passphrase."
note "Actions tidak bisa mengetik passphrase, jadi kunci CI harus polos. Itulah"
note "sebabnya ia tidak boleh sama dengan kunci Anda: privat-nya akan disimpan di"
note "GitHub, dan kalau suatu saat dicurigai, Anda cabut satu itu saja."
printf '\n'

if [[ -f "$ADMIN_KEY" ]]; then
  note "sudah ada: $ADMIN_KEY — dilewati"
else
  say "Sekarang ssh-keygen akan meminta passphrase dua kali. Isi, jangan dikosongkan,"
  say "lalu simpan passphrase itu di password manager Anda."
  pause "Tekan Enter untuk membuat aruna_admin"
  ssh-keygen -t ed25519 -f "$ADMIN_KEY" -C "aruna-admin"
fi

if [[ -f "$DEPLOY_KEY" ]]; then
  note "sudah ada: $DEPLOY_KEY — dilewati"
else
  ssh-keygen -t ed25519 -f "$DEPLOY_KEY" -C "aruna-deploy-ci" -N "" >/dev/null
  printf '  %s✓ dibuat%s %s (tanpa passphrase, disengaja)\n' "$GREEN" "$RESET" "$DEPLOY_KEY"
fi
printf '\n'
pause "Lanjut ke pembuatan VPS?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "IDCloudHost: buat Cloud VPS"
open_url "https://console.idcloudhost.com"
say "Di halaman Create new, setel persis seperti ini:"
printf '\n'
step "Type          : Operating system"
step "OS            : Ubuntu, Version 24.04 LTS"
step "Location      : Indonesia — SouthJKT"
step "Server class  : Basic Standard"
step "Size          : pakai slider kanan — CPU 2, RAM 4 GB, DISK 50 GB"
step "Public IPv4   : dicentang"
step "VPC network   : New network"
step "Username      : deploy"
step "Password      : isi sendiri, simpan di password manager"
step "Init script   : biarkan kosong"
step "Resource name : aruna-prod"
printf '\n'
warn "OS bawaannya AlmaLinux — ganti ke Ubuntu, atau seluruh runbook harus ditulis ulang."
warn "Billing account harus Active dulu, atau tombol Create tidak bekerja."
printf '\n'
pause "Sudah sampai bagian SSH keys?"

salin_ke_clipboard "$ADMIN_KEY.pub"
step "Klik '+ Add SSH key', tempel, beri nama: aruna-admin"
pause "Sudah ditempel?"

salin_ke_clipboard "$DEPLOY_KEY.pub"
step "Tambahkan satu lagi, beri nama: aruna-deploy"
note "Kalau formulir hanya menerima satu kunci, tambahkan yang kedua lewat user profile."
pause "Sudah ditempel?"

printf '\n'
say "Sekarang klik Create new dan tunggu VM-nya menyala."
pause "Sudah menyala?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Catat IP dan tulis ~/.ssh/config"
say "Alamat IPv4 publik ada di halaman detail resource di konsol IDCloudHost."
ask SSH_HOST "Tempel alamat IP VPS:"
if [[ -z "${SSH_HOST:-}" ]]; then
  warn "IP kosong — wizard berhenti. Jalankan lagi setelah VM siap."
  exit 1
fi
write_env SSH_HOST "$SSH_HOST"
write_env SSH_USER "deploy"

mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
touch "$HOME/.ssh/config" && chmod 600 "$HOME/.ssh/config"
if grep -qE '^[[:space:]]*Host[[:space:]]+aruna[[:space:]]*$' "$HOME/.ssh/config"; then
  note "entri 'Host aruna' sudah ada di ~/.ssh/config"
  warn "periksa HostName-nya masih $SSH_HOST kalau VM pernah dibuat ulang"
else
  cat >> "$HOME/.ssh/config" <<EOF

Host aruna
  HostName $SSH_HOST
  User deploy
  IdentityFile $ADMIN_KEY
  IdentitiesOnly yes
EOF
  printf '  %s✓ ditambahkan%s entri "Host aruna" ke ~/.ssh/config\n' "$GREEN" "$RESET"
fi
note "IdentitiesOnly yes penting: tanpa itu ssh menawarkan semua kunci Anda satu per"
note "satu, dan server bisa memutus koneksi karena terlalu banyak percobaan."
printf '\n'
pause "Lanjut menguji koneksinya?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Uji kedua kunci benar-benar diterima"
say "Yang pertama akan menanyakan passphrase aruna_admin, dan sekali menanyakan"
say "apakah sidik jari host-nya dipercaya. Jawab yes."
printf '\n'
if ssh -o ConnectTimeout=15 aruna 'echo BERHASIL: $(whoami)@$(hostname)'; then
  printf '  %s✓ ssh aruna berhasil%s\n' "$GREEN" "$RESET"
else
  warn "ssh aruna gagal. Periksa IP, dan pastikan kunci aruna-admin benar-benar terpasang."
  SKIPPED+=("uji 'ssh aruna' belum berhasil")
fi
printf '\n'

say "Sekarang kunci CI, tanpa interaksi — persis seperti GitHub Actions memakainya."
if ssh -i "$DEPLOY_KEY" -o IdentitiesOnly=yes -o BatchMode=yes -o ConnectTimeout=15 \
     "deploy@$SSH_HOST" true 2>/dev/null; then
  printf '  %s✓ kunci deploy diterima%s\n' "$GREEN" "$RESET"
else
  warn "kunci deploy belum diterima server."
  if confirm "Pasang sekarang lewat ssh-copy-id? (butuh passphrase aruna_admin)"; then
    ssh-copy-id -i "$DEPLOY_KEY.pub" aruna || SKIPPED+=("pasang kunci aruna_deploy di server")
  else
    SKIPPED+=("pasang kunci aruna_deploy di server")
  fi
fi
printf '\n'
pause "Lanjut ke GitHub?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "GitHub: simpan tiga secret"
say "Workflow .github/workflows/deploy.yml membaca tiga nama ini."
printf '\n'
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  set_secret SSH_HOST "$SSH_HOST"
  set_secret SSH_USER "deploy"
  if [[ -f "$DEPLOY_KEY" ]]; then
    set_secret SSH_KEY "$(cat "$DEPLOY_KEY")"
  else
    warn "kunci $DEPLOY_KEY tidak ada — ulangi dari stage 1."
    SKIPPED+=("GitHub secret SSH_KEY")
  fi
  note "SSH_KEY diisi dari berkas, bukan diketik — kunci privat berbaris banyak dan"
  note "menempelnya lewat prompt akan terpotong di baris pertama."
else
  warn "gh belum siap. Jalankan 'gh auth login' lalu ulangi wizard ini,"
  warn "atau isi manual lewat halaman yang akan dibuka."
  open_url "https://github.com/haryosmd/aruna-dewa-web-app/settings/secrets/actions"
  step "New repository secret → SSH_HOST → $SSH_HOST"
  step "New repository secret → SSH_USER → deploy"
  step "New repository secret → SSH_KEY  → isi berkas $DEPLOY_KEY"
  note "Untuk SSH_KEY: jalankan  pbcopy < $DEPLOY_KEY  lalu tempel seluruhnya,"
  note "termasuk baris BEGIN dan END."
  SKIPPED+=("tiga secret GitHub: SSH_HOST, SSH_USER, SSH_KEY")
  pause "Sudah diisi ketiganya?"
fi
printf '\n'
pause "Satu langkah lagi."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Periksa izin Actions menulis ke GHCR"
say "deploy.yml mendorong image ke ghcr.io dengan GITHUB_TOKEN bawaan. Blok"
say "permissions di workflow sudah meminta packages: write, tapi setelan repo"
say "bisa menolaknya — dan gejalanya baru muncul saat rilis pertama."
printf '\n'
open_url "https://github.com/haryosmd/aruna-dewa-web-app/settings/actions"
step "Workflow permissions: pastikan BUKAN 'Read repository contents permission'"
step "  yang mengunci semuanya. 'Read and write permissions' paling aman untuk sekarang."
printf '\n'
pause "Sudah diperiksa?"

finish

printf '  %sLangkah berikutnya%s\n' "$BOLD" "$RESET"
note "1. ssh aruna  — lalu kerjakan Bagian 2 runbook: ufw Cloudflare-only, Docker,"
note "   swap, rotasi log, dan Caddy."
note "2. Siapkan /srv/aruna dengan api.env, web.env, worker.env, .env (POSTGRES_PASSWORD),"
note "   compose.prod.yaml, dan Caddyfile."
note "3. Baru setelah itu rilis pertama boleh dijalankan."
printf '\n'
warn "Kunci privat aruna_admin dan aruna_deploy tidak pernah boleh keluar dari laptop"
warn "Anda, kecuali SSH_KEY yang tadi masuk ke GitHub Secrets. Jangan kirim ke chat."
printf '\n'
